fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    ruby: "puppetlabs/ruby"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.8.0"
    puppetlabs_yum: "stahnma/puppetlabs_yum"
    puppetlabs_apt: "ploperations/puppetlabs_apt"
    mysql: "puppetlabs/mysql"
    unicorn: "ploperations/unicorn"
    rack: "ploperations/rack"
    bundler: "ploperations/bundler"
    nginx: "puppet/nginx"
    inifile: "puppetlabs/inifile"
    apache: "puppetlabs/apache"
    portage: "gentoo/portage"
    puppetdb: "puppetlabs/puppetdb"
  symlinks:
    puppet: "#{source_dir}"
