fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    puppetlabs_yum: "git://github.com/stahnma/puppet-module-puppetlabs_yum"
    puppetlabs_apt: "git://github.com/puppetlabs-operations/puppet-puppetlabs_apt.git"
    interval: "git://github.com/puppetlabs-operations/puppet-interval.git"
    mysql: "git://github.com/puppetlabs-operations/puppetlabs-mysql.git"
    unicorn: "git://github.com/puppetlabs-operations/puppet-unicorn.git"
    rack: "git://github.com/puppetlabs-operations/puppet-rack.git"
    bundler: "git://github.com/puppetlabs-operations/puppet-bundler.git"
    nginx: "git://github.com/jfryman/puppet-nginx.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    portage: "git://github.com/gentoo/puppet-portage.git"
    thin: "git://github.com/danieldreier/puppet-thin.git"
  symlinks:
    puppet: "#{source_dir}"

