#!/bin/bash
# unicorn-puppet         This init script enables the puppetmaster rackup application
#                        via unicorn.
#
# Authors:               Richard Crowley
#                        Naresh V.
#
#    Modified for Debian usage by Matt Carroll
#    Modified for Debian 6+ usage by Zach Leslie
#

### BEGIN INIT INFO
# Provides:          unicorn_puppetmaster
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Puppet Master runnning in Unicorn
### END INIT INFO


lockfile=/var/lock/puppetmaster-unicorn
PIDFILE=/var/run/puppet/puppetmaster_unicorn.pid

RETVAL=0
DAEMON=/var/lib/gems/1.8/bin/unicorn
DAEMON_OPTS="-D -c /etc/puppet/unicorn.conf"

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting Unicorn Pupptemaster server" "unicorn_puppetmaster"
    if start-stop-daemon --start --quiet --oknodo --user $USER --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
}

stop() {
    log_daemon_msg "Stopping Unicorn Pupptemaster server" "unicorn_puppetmaster"
    if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
}

restart() {
    stop
    sleep 1
    start
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status_of_proc -p "$PIDFILE" "${DAEMON}"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit $RETVAL

